apiVersion: v1
kind: Namespace
metadata:
  name: mongo
---
# Секрет с паролем root-пользователя
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secrets
  namespace: mongo
type: Opaque
stringData:
  root-user: root
  root-password: rootpwd
---
# Секрет с keyFile для репликации
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-keyfile
  namespace: mongo
type: Opaque
stringData:
  keyfile: |
    hgsg21hgsj2hg812gh12g1hg12g1hg12
---
# инит-конфигмап для mongo-a
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-a-init
  namespace: mongo
data:
  init.js: |
    // Init script for mongo-a (standalone)
    const dbName = "dbA";
    const localUser = "userA";
    const localPass = "passwordA";
    const sharedUser = "reader";
    const sharedPass = "passwordR";

    const seedValue = () => Math.random().toString(36).slice(2, 10);

    const dbInstance = db.getSiblingDB(dbName);
    dbInstance.sample.insertMany([
      { key: seedValue(), createdAt: new Date() },
      { key: seedValue(), createdAt: new Date() },
    ]);

    dbInstance.createUser({
      user: localUser,
      pwd: localPass,
      roles: [{ role: "readWrite", db: dbName }],
    });

    dbInstance.createUser({
      user: sharedUser,
      pwd: sharedPass,
      roles: [{ role: "read", db: dbName }],
    });
---
# init-конфигмап для mongo-b
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-b-init
  namespace: mongo
data:
  init.js: |
    // Init script for mongo-b (standalone)
    const dbName = "dbB";
    const localUser = "userB";
    const localPass = "passwordB";
    const sharedUser = "reader";
    const sharedPass = "passwordR";

    const seedValue = () => Math.random().toString(36).slice(2, 10);

    const dbInstance = db.getSiblingDB(dbName);
    dbInstance.sample.insertMany([
      { key: seedValue(), createdAt: new Date() },
      { key: seedValue(), createdAt: new Date() },
    ]);

    dbInstance.createUser({
      user: localUser,
      pwd: localPass,
      roles: [{ role: "readWrite", db: dbName }],
    });

    dbInstance.createUser({
      user: sharedUser,
      pwd: sharedPass,
      roles: [{ role: "read", db: dbName }],
    });
---
# КонфигМап для репликации mongo-b
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-b-rs-init
  namespace: mongo
data:
  rs-init.js: |
    // Идемпотентная инициализация репликасета rs-b

    let alreadyInited = false;
    try {
      const status = rs.status();
      if (status.ok === 1) {
        print("Replica set already initialized, skipping rs.initiate");
        alreadyInited = true;
      }
    } catch (e) {
      print("Replica set not yet initialized, will call rs.initiate");
    }

    if (!alreadyInited) {
      rs.initiate({
        _id: "rs-b",
        members: [
          { _id: 0, host: "mongo-b-0.svc-mongo-b:27017" },
          { _id: 1, host: "mongo-b-1.svc-mongo-b:27017" },
          { _id: 2, host: "mongo-b-2.svc-mongo-b:27017" }
        ]
      });
      print("Replica set rs-b initialized");
    }

    // Высвечиваем текущий статус
    try {
      printjson(rs.status());
    } catch (e) {
      print("Error getting rs.status(): " + e);
    }
---
# Job для настройки репликации mongo-b
---
apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-b-rs-init
  namespace: mongo
spec:
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-mongo-b
          image: mongo:7.0
          command:
            - bash
            - -c
            - |
              echo "Waiting for mongo-b-0 to be ready..."
              until mongosh --host mongo-b-0.svc-mongo-b:27017 \
                -u "$MONGO_INITDB_ROOT_USERNAME" \
                -p "$MONGO_INITDB_ROOT_PASSWORD" \
                --authenticationDatabase admin \
                --quiet \
                --eval 'db.adminCommand({ ping: 1 })' >/dev/null 2>&1; do
                  echo "Mongo is not ready yet, retrying..."
                  sleep 3
              done
              echo "Mongo is ready, proceeding to rs init"
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets
                  key: root-user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets
                  key: root-password
      containers:
        - name: rs-init
          image: mongo:7.0
          command:
            - bash
            - -c
            - |
              echo "Running replica set initialization script..."
              mongosh --host mongo-b-0.svc-mongo-b:27017 \
                -u "$MONGO_INITDB_ROOT_USERNAME" \
                -p "$MONGO_INITDB_ROOT_PASSWORD" \
                --authenticationDatabase admin \
                /rs-init.js
              echo "Replica set init finished"
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets
                  key: root-user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets
                  key: root-password
          volumeMounts:
            - name: rs-init-script
              mountPath: /rs-init.js
              subPath: rs-init.js
      volumes:
        - name: rs-init-script
          configMap:
            name: mongo-b-rs-init
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-a
  namespace: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
      instance: mongo-a
  template:
    metadata:
      labels:
        app: mongo
        instance: mongo-a
    spec:
      containers:
        - name: mongo
          image: mongo:7.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets
                  key: root-user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets
                  key: root-password
          volumeMounts:
            - name: data
              mountPath: /data/db
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d/init.js
              subPath: init.js
      volumes:
        - name: data
          emptyDir: {}
        - name: init-script
          configMap:
            name: mongo-a-init
---
# Сервис для mongo-a
---
apiVersion: v1
kind: Service
metadata:
  name: svc-mongo-a
  namespace: mongo
spec:
  selector:
    app: mongo
    instance: mongo-a
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
---
# СтейтфулСет для mongo-b из 3 копий
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-b
  namespace: mongo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongo
      instance: mongo-b
  template:
    metadata:
      labels:
        app: mongo
        instance: mongo-b
    spec:
      containers:
        - name: mongo
          image: mongo:7.0
          args:
            - "--replSet"
            - "rs-b"
            - "--bind_ip_all"
            - "--keyFile"
            - "/etc/mongo-keyfile/keyfile"
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets
                  key: root-user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets
                  key: root-password
          volumeMounts:
            - name: data
              mountPath: /data/db
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d/init.js
              subPath: init.js
            - name: keyfile
              mountPath: /etc/mongo-keyfile/keyfile
              readOnly: true
      volumes:
        - name: data
          emptyDir: {}
        - name: init-script
          configMap:
            name: mongo-b-init
        - name: keyfile
          secret:
            secretName: mongo-keyfile
            defaultMode: 0600
---
# Сервис для mongo-b
---
apiVersion: v1
kind: Service
metadata:
  name: svc-mongo-b
  namespace: mongo
spec:
  selector:
    app: mongo
    instance: mongo-b
  clusterIP: None
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
