---
apiVersion: v1
kind: Namespace
metadata:
  name: dbs
---
apiVersion: v1
kind: Secret
metadata:
  name: pg-secrets
  namespace: dbs
type: Opaque
stringData:
  POSTGRES_PASSWORD_A: "passwordA"
  POSTGRES_PASSWORD_B: "passwordB"
  #FDW_READER_PASSWORD: "fdw_reader_pass"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-a-init-sql
  namespace: dbs
data:
  01-init.sql: |
    CREATE TABLE IF NOT EXISTS a_table1 (
        id serial PRIMARY KEY,
        info text,
        created_at timestamptz DEFAULT now()
    );
    CREATE TABLE IF NOT EXISTS a_table2 (
        id serial PRIMARY KEY,
        value integer,
        created_at timestamptz DEFAULT now()
    );
    INSERT INTO a_table1 (info) VALUES ('First_value'),('Second_value'),('Third_value') ON CONFLICT DO NOTHING;
    INSERT INTO a_table2 (value) VALUES (100),(200),(300) ON CONFLICT DO NOTHING;

    -- Прикладной пользователь A
    CREATE ROLE user_a LOGIN PASSWORD 'user_a_pass';

    -- Привилегии
    REVOKE ALL ON SCHEMA public FROM PUBLIC;
    GRANT USAGE ON SCHEMA public TO user_a;
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO user_a;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO user_a;

    -- Пользователь для FDW-чтения с B
    CREATE ROLE fdw_reader LOGIN PASSWORD 'fdw_reader_pass';
    GRANT CONNECT ON DATABASE db_a TO fdw_reader;
    GRANT USAGE ON SCHEMA public TO fdw_reader;
    GRANT SELECT ON a_table1, a_table2 TO fdw_reader;
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-b-init-sql
  namespace: dbs
data:
  01-init.sql: |
    CREATE TABLE IF NOT EXISTS b_table1 (
        id serial PRIMARY KEY,
        note text,
        created_at timestamptz DEFAULT now()
    );
    CREATE TABLE IF NOT EXISTS b_table2 (
        id serial PRIMARY KEY,
        amount numeric,
        created_at timestamptz DEFAULT now()
    );
    INSERT INTO b_table1 (note) VALUES ('some1'),('some2') ON CONFLICT DO NOTHING;
    INSERT INTO b_table2 (amount) VALUES (12.5),(34.0) ON CONFLICT DO NOTHING;

    -- Прикладной пользователь B
    CREATE ROLE user_b LOGIN PASSWORD 'user_b_pass';
    REVOKE ALL ON SCHEMA public FROM PUBLIC;
    GRANT USAGE ON SCHEMA public TO user_b;
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO user_b;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO user_b;

    -- ---------- FDW к Postgres-A ----------
    CREATE EXTENSION IF NOT EXISTS postgres_fdw;

    -- Внешний сервер указывает на сервис A
    CREATE SERVER IF NOT EXISTS server_a
      FOREIGN DATA WRAPPER postgres_fdw
      OPTIONS (host 'postgres-a-svc', port '5432', dbname 'db_a');

    -- ВАЖНО: мэппинг для postgres (init-скрипт выполняется под суперпользователем)
    CREATE USER MAPPING IF NOT EXISTS FOR postgres
      SERVER server_a OPTIONS (user 'fdw_reader', password 'fdw_reader_pass');

    -- Мэппинг для прикладного пользователя
    CREATE USER MAPPING IF NOT EXISTS FOR user_b
      SERVER server_a OPTIONS (user 'fdw_reader', password 'fdw_reader_pass');

    -- Импорт внешних таблиц из A (в схему public B)
    IMPORT FOREIGN SCHEMA public LIMIT TO (a_table1, a_table2)
      FROM SERVER server_a INTO public;

    -- Права на импортированные foreign tables и доступ к серверу
    GRANT USAGE ON SCHEMA public TO user_b;
    GRANT SELECT ON a_table1, a_table2 TO user_b;
    GRANT USAGE ON FOREIGN SERVER server_a TO user_b;
---
# PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata-a-pvc
  namespace: dbs
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata-b-pvc
  namespace: dbs
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
---
# -------------------------------
# POSTGRES-A DEPLOYMENT
# -------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-a
  namespace: dbs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-a
  template:
    metadata:
      labels:
        app: postgres-a
    spec:
      #initContainers:
      #- name: clean-pv
       # image: busybox
        #command: ["sh", "-c", "rm -rf /var/lib/postgresql/data/*"]
        #volumeMounts:
        #- name: pgdata
          #mountPath: /var/lib/postgresql/data
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: "db_a"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-secrets
              key: POSTGRES_PASSWORD_A
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data
        - name: init-sql
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: pgdata
        persistentVolumeClaim:
          claimName: pgdata-a-pvc
      - name: init-sql
        configMap:
          name: postgres-a-init-sql
          defaultMode: 0644
---
# -------------------------------
# POSTGRES-B DEPLOYMENT (ожидание A)
# -------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-b
  namespace: dbs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-b
  template:
    metadata:
      labels:
        app: postgres-b
    spec:
      initContainers:
      - name: wait-for-a
        image: postgres:15
        command:
          - sh
          - -c
          - |
            until pg_isready -h postgres-a-svc -p 5432 -q; do
              echo "waiting for postgres-a";
              sleep 2;
            done
      #- name: clean-pv
        #image: busybox
        #command: ["sh", "-c", "rm -rf /var/lib/postgresql/data/*"]
        #volumeMounts:
        #- name: pgdata
          #mountPath: /var/lib/postgresql/data
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: "db_b"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-secrets
              key: POSTGRES_PASSWORD_B
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data
        - name: init-sql
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: pgdata
        persistentVolumeClaim:
          claimName: pgdata-b-pvc
      - name: init-sql
        configMap:
          name: postgres-b-init-sql
          defaultMode: 0644
---
# -------------------------------
# SERVICES
# -------------------------------
apiVersion: v1
kind: Service
metadata:
  name: postgres-a-svc
  namespace: dbs
spec:
  selector:
    app: postgres-a
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-b-svc
  namespace: dbs
spec:
  selector:
    app: postgres-b
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
